In [25]:
import pandas as pd
data = pd.read_csv('../input/question-1/main.csv')
print(data)

    Year  Population     Total  Violent  Property  Murder  Forcible_Rape  \
0   1960   179323175   3384200   288460   3095700    9110          17190
1   1961   182992000   3488000   289390   3198600    8740          17220
2   1962   185771000   3752200   301510   3450700    8530          17550
3   1963   188483000   4109500   316970   3792500    8640          17650
4   1964   191141000   4564600   364220   4200400    9360          21420
5   1965   193526000   4739400   387390   4352000    9960          23410
6   1966   195576000   5223500   430180   4793300   11040          25820
7   1967   197457000   5903400   499930   5403500   12240          27620
8   1968   199399000   6720200   595010   6125200   13800          31670
9   1969   201385000   7410900   661870   6749000   14760          37170
10  1970   203235298   8098000   738820   7359200   16000          37990
11  1971   206212000   8588200   816500   7771700   17780          42260
12  1972   208230000   8248800   834900   7413900   18670          46850
13  1973   209851000   8718100   875910   7842200   19640          51400
14  1974   211392000  10253400   974720   9278700   20710          55400
15  1975   213124000  11292400  1039710  10252700   20510          56090
16  1976   214659000  11349700  1004210  10345500   18780          57080
17  1977   216332000  10984500  1029580   9955000   19120          63500
18  1978   218059000  11209000  1085550  10123400   19560          67610
19  1979   220099000  12249500  1208030  11041500   21460          76390
20  1980   225349264  13408300  1344520  12063700   23040          82990
21  1981   229146000  13423800  1361820  12061900   22520          82500
22  1982   231534000  12974400  1322390  11652000   21010          78770
23  1983   233981000  12108600  1258090  10850500   19310          78920
24  1984   236158000  11881800  1273280  10608500   18690          84230
25  1985   238740000  12431400  1328800  11102600   18980          88670
26  1986   240132887  13211869  1489169  11722700   20613          91459
27  1987   242282918  13508700  1483999  12024700   20096          91110
28  1988   245807000  13923100  1566220  12356900   20680          92490
29  1989   248239000  14251400  1646040  12605400   21500          94500
30  1990   248709873  14475600  1820130  12655500   23440         102560
31  1991   252177000  14872900  1911770  12961100   24700         106590
32  1992   255082000  14438200  1932270  12505900   23760         109060
33  1993   257908000  14144800  1926020  12218800   24530         106010
34  1994   260341000  13989500  1857670  12131900   23330         102220
35  1995   262755000  13862700  1798790  12063900   21610          97470
36  1996   265228572  13493863  1688540  11805300   19650          96250
37  1997   267637000  13194571  1634770  11558175   18208          96153
38  1998   270296000  12475634  1531044  10944590   16914          93103
39  1999   272690813  11634378  1426044  10208334   15522          89411
40  2000   281421906  11608072  1425486  10182586   15586          90178
41  2001   285317559  11876669  1439480  10437480   16037          90863
42  2002   287973924  11878954  1423677  10455277   16229          95235
43  2003   290690788  11826538  1383676  10442862   16528          93883
44  2004   293656842  11679474  1360088  10319386   16148          95089
45  2005   296507061  11565499  1390745  10174754   16740          94347
46  2006   299398484  11401511  1418043   9983568   17030          92757
47  2007   301621157  11251828  1408337   9843481   16929          90427
48  2008   304374846  11160543  1392628   9767915   16442          90479
49  2009   307006550  10762956  1325896   9337060   15399          89241
50  2010   309330219  10363873  1251248   9112625   14772          85593
51  2011   311587816  10258774  1206031   9052743   14661          84175
52  2012   313873685  10219059  1217067   9001992   14866          85141
53  2013   316497531   9850445  1199684   8650761   14319          82109
54  2014   318857056   9475816  1197987   8277829   14249          84041

    Robbery  Aggravated_assault  Burglary  Larceny_Theft  Vehicle_Theft
0    107840              154320    912100        1855400         328200
1    106670              156760    949600        1913000         336000
2    110860              164570    994300        2089600         366800
3    116470              174210   1086400        2297800         408300
4    130390              203050   1213200        2514400         472800
5    138690              215330   1282500        2572600         496900
6    157990              235330   1410100        2822000         561200
7    202910              257160   1632100        3111600         659800
8    262840              286700   1858900        3482700         783600
9    298850              311090   1981900        3888600         878500
10   349860              334970   2205000        4225800         928400
11   387700              368760   2399300        4424200         948200
12   376290              393090   2375500        4151200         887200
13   384220              420650   2565500        4347900         928800
14   442400              456210   3039200        5262500         977100
15   470500              492620   3265300        5977700        1009600
16   427810              500530   3108700        6270800         966000
17   412610              534350   3071500        5905700         977700
18   426930              571460   3128300        5991000        1004100
19   480700              629480   3327700        6601000        1112800
20   565840              672650   3795200        7136900        1131700
21   592910              663900   3779700        7194400        1087800
22   553130              669480   3447100        7142500        1062400
23   506570              653290   3129900        6712800        1007900
24   485010              685350   2984400        6591900        1032200
25   497870              723250   3073300        6926400        1102900
26   542775              834322   3241410        7257153        1224137
27   517704              855088   3236184        7499900        1288674
28   542970              910090   3218100        7705900        1432900
29   578330              951710   3168200        7872400        1564800
30   639270             1054860   3073900        7945700        1635900
31   687730             1092740   3157200        8142200        1661700
32   672480             1126970   2979900        7915200        1610800
33   659870             1135610   2834800        7820900        1563100
34   618950             1113180   2712800        7879800        1539300
35   580510             1099210   2593800        7997700        1472400
36   535590             1037050   2506400        7904700        1394200
37   498534             1023201   2460526        7743760        1354189
38   446625              974402   2329950        7373886        1240754
39   409371              911740   2100739        6955520        1152075
40   408016              911706   2050992        6971590        1160002
41   423557              909023   2116531        7092267        1228391
42   420806              891407   2151252        7057370        1246646
43   414235              859030   2154834        7026802        1261226
44   401470              847381   2144446        6937089        1237851
45   417438              862220   2155448        6783447        1235859
46   447403              860853   2183746        6607013        1192809
47   445125              855856   2176140        6568572        1095769
48   443574              842134   2228474        6588046         958629
49   408742              812514   2203313        6338095         795652
50   369089              781844   2168457        6204601         739565
51   354772              752423   2185140        6151095         716508
52   355051              762009   2109932        6168874         723186
53   345095              726575   1931835        6018632         700294
54   325802              741291   1729806        5858496         689527

In [26]:
del data["Total"]
print(data)

    Year  Population  Violent  Property  Murder  Forcible_Rape  Robbery  \
0   1960   179323175   288460   3095700    9110          17190   107840
1   1961   182992000   289390   3198600    8740          17220   106670
2   1962   185771000   301510   3450700    8530          17550   110860
3   1963   188483000   316970   3792500    8640          17650   116470
4   1964   191141000   364220   4200400    9360          21420   130390
5   1965   193526000   387390   4352000    9960          23410   138690
6   1966   195576000   430180   4793300   11040          25820   157990
7   1967   197457000   499930   5403500   12240          27620   202910
8   1968   199399000   595010   6125200   13800          31670   262840
9   1969   201385000   661870   6749000   14760          37170   298850
10  1970   203235298   738820   7359200   16000          37990   349860
11  1971   206212000   816500   7771700   17780          42260   387700
12  1972   208230000   834900   7413900   18670          46850   376290
13  1973   209851000   875910   7842200   19640          51400   384220
14  1974   211392000   974720   9278700   20710          55400   442400
15  1975   213124000  1039710  10252700   20510          56090   470500
16  1976   214659000  1004210  10345500   18780          57080   427810
17  1977   216332000  1029580   9955000   19120          63500   412610
18  1978   218059000  1085550  10123400   19560          67610   426930
19  1979   220099000  1208030  11041500   21460          76390   480700
20  1980   225349264  1344520  12063700   23040          82990   565840
21  1981   229146000  1361820  12061900   22520          82500   592910
22  1982   231534000  1322390  11652000   21010          78770   553130
23  1983   233981000  1258090  10850500   19310          78920   506570
24  1984   236158000  1273280  10608500   18690          84230   485010
25  1985   238740000  1328800  11102600   18980          88670   497870
26  1986   240132887  1489169  11722700   20613          91459   542775
27  1987   242282918  1483999  12024700   20096          91110   517704
28  1988   245807000  1566220  12356900   20680          92490   542970
29  1989   248239000  1646040  12605400   21500          94500   578330
30  1990   248709873  1820130  12655500   23440         102560   639270
31  1991   252177000  1911770  12961100   24700         106590   687730
32  1992   255082000  1932270  12505900   23760         109060   672480
33  1993   257908000  1926020  12218800   24530         106010   659870
34  1994   260341000  1857670  12131900   23330         102220   618950
35  1995   262755000  1798790  12063900   21610          97470   580510
36  1996   265228572  1688540  11805300   19650          96250   535590
37  1997   267637000  1634770  11558175   18208          96153   498534
38  1998   270296000  1531044  10944590   16914          93103   446625
39  1999   272690813  1426044  10208334   15522          89411   409371
40  2000   281421906  1425486  10182586   15586          90178   408016
41  2001   285317559  1439480  10437480   16037          90863   423557
42  2002   287973924  1423677  10455277   16229          95235   420806
43  2003   290690788  1383676  10442862   16528          93883   414235
44  2004   293656842  1360088  10319386   16148          95089   401470
45  2005   296507061  1390745  10174754   16740          94347   417438
46  2006   299398484  1418043   9983568   17030          92757   447403
47  2007   301621157  1408337   9843481   16929          90427   445125
48  2008   304374846  1392628   9767915   16442          90479   443574
49  2009   307006550  1325896   9337060   15399          89241   408742
50  2010   309330219  1251248   9112625   14772          85593   369089
51  2011   311587816  1206031   9052743   14661          84175   354772
52  2012   313873685  1217067   9001992   14866          85141   355051
53  2013   316497531  1199684   8650761   14319          82109   345095
54  2014   318857056  1197987   8277829   14249          84041   325802

    Aggravated_assault  Burglary  Larceny_Theft  Vehicle_Theft
0               154320    912100        1855400         328200
1               156760    949600        1913000         336000
2               164570    994300        2089600         366800
3               174210   1086400        2297800         408300
4               203050   1213200        2514400         472800
5               215330   1282500        2572600         496900
6               235330   1410100        2822000         561200
7               257160   1632100        3111600         659800
8               286700   1858900        3482700         783600
9               311090   1981900        3888600         878500
10              334970   2205000        4225800         928400
11              368760   2399300        4424200         948200
12              393090   2375500        4151200         887200
13              420650   2565500        4347900         928800
14              456210   3039200        5262500         977100
15              492620   3265300        5977700        1009600
16              500530   3108700        6270800         966000
17              534350   3071500        5905700         977700
18              571460   3128300        5991000        1004100
19              629480   3327700        6601000        1112800
20              672650   3795200        7136900        1131700
21              663900   3779700        7194400        1087800
22              669480   3447100        7142500        1062400
23              653290   3129900        6712800        1007900
24              685350   2984400        6591900        1032200
25              723250   3073300        6926400        1102900
26              834322   3241410        7257153        1224137
27              855088   3236184        7499900        1288674
28              910090   3218100        7705900        1432900
29              951710   3168200        7872400        1564800
30             1054860   3073900        7945700        1635900
31             1092740   3157200        8142200        1661700
32             1126970   2979900        7915200        1610800
33             1135610   2834800        7820900        1563100
34             1113180   2712800        7879800        1539300
35             1099210   2593800        7997700        1472400
36             1037050   2506400        7904700        1394200
37             1023201   2460526        7743760        1354189
38              974402   2329950        7373886        1240754
39              911740   2100739        6955520        1152075
40              911706   2050992        6971590        1160002
41              909023   2116531        7092267        1228391
42              891407   2151252        7057370        1246646
43              859030   2154834        7026802        1261226
44              847381   2144446        6937089        1237851
45              862220   2155448        6783447        1235859
46              860853   2183746        6607013        1192809
47              855856   2176140        6568572        1095769
48              842134   2228474        6588046         958629
49              812514   2203313        6338095         795652
50              781844   2168457        6204601         739565
51              752423   2185140        6151095         716508
52              762009   2109932        6168874         723186
53              726575   1931835        6018632         700294
54              741291   1729806        5858496         689527

In [27]:
population = data["Population"]
print(population)

0     179323175
1     182992000
2     185771000
3     188483000
4     191141000
5     193526000
6     195576000
7     197457000
8     199399000
9     201385000
10    203235298
11    206212000
12    208230000
13    209851000
14    211392000
15    213124000
16    214659000
17    216332000
18    218059000
19    220099000
20    225349264
21    229146000
22    231534000
23    233981000
24    236158000
25    238740000
26    240132887
27    242282918
28    245807000
29    248239000
30    248709873
31    252177000
32    255082000
33    257908000
34    260341000
35    262755000
36    265228572
37    267637000
38    270296000
39    272690813
40    281421906
41    285317559
42    287973924
43    290690788
44    293656842
45    296507061
46    299398484
47    301621157
48    304374846
49    307006550
50    309330219
51    311587816
52    313873685
53    316497531
54    318857056
Name: Population, dtype: int64

In [28]:
popul = []
for i in range(9, len(population) + 1, 10):
    popul.append(population.iloc[i])
popul.append(int(population.iloc[-1]))
print(popul)

[201385000, 220099000, 248239000, 272690813, 307006550, 318857056]

In [29]:
del data["Population"]
print(data)

    Year  Violent  Property  Murder  Forcible_Rape  Robbery  \
0   1960   288460   3095700    9110          17190   107840
1   1961   289390   3198600    8740          17220   106670
2   1962   301510   3450700    8530          17550   110860
3   1963   316970   3792500    8640          17650   116470
4   1964   364220   4200400    9360          21420   130390
5   1965   387390   4352000    9960          23410   138690
6   1966   430180   4793300   11040          25820   157990
7   1967   499930   5403500   12240          27620   202910
8   1968   595010   6125200   13800          31670   262840
9   1969   661870   6749000   14760          37170   298850
10  1970   738820   7359200   16000          37990   349860
11  1971   816500   7771700   17780          42260   387700
12  1972   834900   7413900   18670          46850   376290
13  1973   875910   7842200   19640          51400   384220
14  1974   974720   9278700   20710          55400   442400
15  1975  1039710  10252700   20510          56090   470500
16  1976  1004210  10345500   18780          57080   427810
17  1977  1029580   9955000   19120          63500   412610
18  1978  1085550  10123400   19560          67610   426930
19  1979  1208030  11041500   21460          76390   480700
20  1980  1344520  12063700   23040          82990   565840
21  1981  1361820  12061900   22520          82500   592910
22  1982  1322390  11652000   21010          78770   553130
23  1983  1258090  10850500   19310          78920   506570
24  1984  1273280  10608500   18690          84230   485010
25  1985  1328800  11102600   18980          88670   497870
26  1986  1489169  11722700   20613          91459   542775
27  1987  1483999  12024700   20096          91110   517704
28  1988  1566220  12356900   20680          92490   542970
29  1989  1646040  12605400   21500          94500   578330
30  1990  1820130  12655500   23440         102560   639270
31  1991  1911770  12961100   24700         106590   687730
32  1992  1932270  12505900   23760         109060   672480
33  1993  1926020  12218800   24530         106010   659870
34  1994  1857670  12131900   23330         102220   618950
35  1995  1798790  12063900   21610          97470   580510
36  1996  1688540  11805300   19650          96250   535590
37  1997  1634770  11558175   18208          96153   498534
38  1998  1531044  10944590   16914          93103   446625
39  1999  1426044  10208334   15522          89411   409371
40  2000  1425486  10182586   15586          90178   408016
41  2001  1439480  10437480   16037          90863   423557
42  2002  1423677  10455277   16229          95235   420806
43  2003  1383676  10442862   16528          93883   414235
44  2004  1360088  10319386   16148          95089   401470
45  2005  1390745  10174754   16740          94347   417438
46  2006  1418043   9983568   17030          92757   447403
47  2007  1408337   9843481   16929          90427   445125
48  2008  1392628   9767915   16442          90479   443574
49  2009  1325896   9337060   15399          89241   408742
50  2010  1251248   9112625   14772          85593   369089
51  2011  1206031   9052743   14661          84175   354772
52  2012  1217067   9001992   14866          85141   355051
53  2013  1199684   8650761   14319          82109   345095
54  2014  1197987   8277829   14249          84041   325802

    Aggravated_assault  Burglary  Larceny_Theft  Vehicle_Theft
0               154320    912100        1855400         328200
1               156760    949600        1913000         336000
2               164570    994300        2089600         366800
3               174210   1086400        2297800         408300
4               203050   1213200        2514400         472800
5               215330   1282500        2572600         496900
6               235330   1410100        2822000         561200
7               257160   1632100        3111600         659800
8               286700   1858900        3482700         783600
9               311090   1981900        3888600         878500
10              334970   2205000        4225800         928400
11              368760   2399300        4424200         948200
12              393090   2375500        4151200         887200
13              420650   2565500        4347900         928800
14              456210   3039200        5262500         977100
15              492620   3265300        5977700        1009600
16              500530   3108700        6270800         966000
17              534350   3071500        5905700         977700
18              571460   3128300        5991000        1004100
19              629480   3327700        6601000        1112800
20              672650   3795200        7136900        1131700
21              663900   3779700        7194400        1087800
22              669480   3447100        7142500        1062400
23              653290   3129900        6712800        1007900
24              685350   2984400        6591900        1032200
25              723250   3073300        6926400        1102900
26              834322   3241410        7257153        1224137
27              855088   3236184        7499900        1288674
28              910090   3218100        7705900        1432900
29              951710   3168200        7872400        1564800
30             1054860   3073900        7945700        1635900
31             1092740   3157200        8142200        1661700
32             1126970   2979900        7915200        1610800
33             1135610   2834800        7820900        1563100
34             1113180   2712800        7879800        1539300
35             1099210   2593800        7997700        1472400
36             1037050   2506400        7904700        1394200
37             1023201   2460526        7743760        1354189
38              974402   2329950        7373886        1240754
39              911740   2100739        6955520        1152075
40              911706   2050992        6971590        1160002
41              909023   2116531        7092267        1228391
42              891407   2151252        7057370        1246646
43              859030   2154834        7026802        1261226
44              847381   2144446        6937089        1237851
45              862220   2155448        6783447        1235859
46              860853   2183746        6607013        1192809
47              855856   2176140        6568572        1095769
48              842134   2228474        6588046         958629
49              812514   2203313        6338095         795652
50              781844   2168457        6204601         739565
51              752423   2185140        6151095         716508
52              762009   2109932        6168874         723186
53              726575   1931835        6018632         700294
54              741291   1729806        5858496         689527

In [34]:
data = data.groupby((data.Year//10)*10).sum()

In [35]:
print(popul)
data.insert(loc = 1, column = 'Population', value = popul)

[201385000, 220099000, 248239000, 272690813, 307006550, 318857056]

In [36]:
print(data)

       Year  Population   Violent   Property  Murder  Forcible_Rape  Robbery  \
Year
1960  19645   201385000   4134930   45160900  106180         236720  1633510
1970  19745   220099000   9607930   91383800  192230         554570  4159020
1980  19845   248239000  14074328  117048900  206439         865639  5383109
1990  19945   272690813  17527048  119053499  211664         998827  5748930
2000  20045   307006550  13968056  100944369  163068         922499  4230366
2010  10060   318857056   6072017   44095950   72867         421059  1749809

      Aggravated_assault  Burglary  Larceny_Theft  Vehicle_Theft
Year
1960             2158520  13321100       26547700        5292100
1970             4702120  28486000       53157800        9739900
1980             7619130  33073494       72040253       11935411
1990            10568963  26750015       77679366       14624418
2000             8652124  21565176       67970291       11412834
2010             3764142  10125170       30401698        3569080

In [37]:
del data["Year"]
print(data)

      Population   Violent   Property  Murder  Forcible_Rape  Robbery  \
Year
1960   201385000   4134930   45160900  106180         236720  1633510
1970   220099000   9607930   91383800  192230         554570  4159020
1980   248239000  14074328  117048900  206439         865639  5383109
1990   272690813  17527048  119053499  211664         998827  5748930
2000   307006550  13968056  100944369  163068         922499  4230366
2010   318857056   6072017   44095950   72867         421059  1749809

      Aggravated_assault  Burglary  Larceny_Theft  Vehicle_Theft
Year
1960             2158520  13321100       26547700        5292100
1970             4702120  28486000       53157800        9739900
1980             7619130  33073494       72040253       11935411
1990            10568963  26750015       77679366       14624418
2000             8652124  21565176       67970291       11412834
2010             3764142  10125170       30401698        3569080

In [39]:
data.to_csv('main.csv')

In [40]:
import pandas as pd
data = pd.read_csv('../input/question-1/main.csv')
del data["Total"]
population = data["Population"]
popul = []
for i in range(9, len(population) + 1, 10):
    popul.append(population.iloc[i])
popul.append(int(population.iloc[-1]))
del data["Population"]
data = data.groupby((data.Year//10)*10).sum()
data.insert(loc = 1, column = 'Population', value = popul)
del data["Year"]
print(data)

      Population   Violent   Property  Murder  Forcible_Rape  Robbery  \
Year
1960   201385000   4134930   45160900  106180         236720  1633510
1970   220099000   9607930   91383800  192230         554570  4159020
1980   248239000  14074328  117048900  206439         865639  5383109
1990   272690813  17527048  119053499  211664         998827  5748930
2000   307006550  13968056  100944369  163068         922499  4230366
2010   318857056   6072017   44095950   72867         421059  1749809

      Aggravated_assault  Burglary  Larceny_Theft  Vehicle_Theft
Year
1960             2158520  13321100       26547700        5292100
1970             4702120  28486000       53157800        9739900
1980             7619130  33073494       72040253       11935411
1990            10568963  26750015       77679366       14624418
2000             8652124  21565176       67970291       11412834
2010             3764142  10125170       30401698        3569080

In [49]:
import pandas as pd
data = pd.read_csv('../input/question-2/main.csv')
data = data[["age", "occupation"]]
print(data)

     age     occupation
0     24     technician
1     53          other
2     23         writer
3     24     technician
4     33          other
5     42      executive
6     57  administrator
7     36  administrator
8     29        student
9     53         lawyer
10    39          other
11    28          other
12    47       educator
13    45      scientist
14    49       educator
15    21  entertainment
16    30     programmer
17    35          other
18    40      librarian
19    42      homemaker
20    26         writer
21    25         writer
22    30         artist
23    21         artist
24    39       engineer
25    49       engineer
26    40      librarian
27    32         writer
28    41     programmer
29     7        student
..   ...            ...
913   44          other
914   50  entertainment
915   27       engineer
916   22        student
917   40      scientist
918   25          other
919   30         artist
920   20        student
921   29  administrator
922   21        student
923   29          other
924   18       salesman
925   49  entertainment
926   23     programmer
927   21        student
928   44      scientist
929   28      scientist
930   60       educator
931   58       educator
932   28        student
933   61       engineer
934   42         doctor
935   24          other
936   48       educator
937   38     technician
938   26        student
939   32  administrator
940   20        student
941   48      librarian
942   22        student

[943 rows x 2 columns]

In [51]:
result = data.groupby('occupation').agg({'age': ['min', 'max']})
print(result)

              age
              min max
occupation
administrator  21  70
artist         19  48
doctor         28  64
educator       23  63
engineer       22  70
entertainment  15  50
executive      22  69
healthcare     22  62
homemaker      20  50
lawyer         21  53
librarian      23  69
marketing      24  55
none           11  55
other          13  64
programmer     20  63
retired        51  73
salesman       18  66
scientist      23  55
student         7  42
technician     21  55
writer         18  60

In [52]:
result.to_csv('main.csv')

In [56]:
import pandas as pd
data = pd.read_csv('../input/question-3/main.csv')
data = data[["Team", "Yellow Cards", "Red Cards"]]
print(data)

                   Team  Yellow Cards  Red Cards
0               Croatia             9          0
1        Czech Republic             7          0
2               Denmark             4          0
3               England             5          0
4                France             6          0
5               Germany             4          0
6                Greece             9          1
7                 Italy            16          0
8           Netherlands             5          0
9                Poland             7          1
10             Portugal            12          0
11  Republic of Ireland             6          1
12               Russia             6          0
13                Spain            11          0
14               Sweden             7          0
15              Ukraine             5          0

In [57]:
result = data.sort_values(by = ['Red Cards', 'Yellow Cards'], ascending = False)
print(result)

                   Team  Yellow Cards  Red Cards
6                Greece             9          1
9                Poland             7          1
11  Republic of Ireland             6          1
7                 Italy            16          0
10             Portugal            12          0
13                Spain            11          0
0               Croatia             9          0
1        Czech Republic             7          0
14               Sweden             7          0
4                France             6          0
12               Russia             6          0
3               England             5          0
8           Netherlands             5          0
15              Ukraine             5          0
2               Denmark             4          0
5               Germany             4          0

In [58]:
result.to_csv('main.csv')